/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as DepositScriptJson } from "../Deposit.ral.json";
import { default as SwapScriptJson } from "../Swap.ral.json";
import { default as WithdrawALPHScriptJson } from "../WithdrawALPH.ral.json";
import { default as WithdrawTokenScriptJson } from "../WithdrawToken.ral.json";

export const Deposit = new ExecutableScript<{
  ico: HexString;
  tokenId: HexString;
  amountIcoTokens: bigint;
}>(Script.fromJson(DepositScriptJson));
export const Swap = new ExecutableScript<{
  ico: HexString;
  amountIcoTokens: bigint;
}>(Script.fromJson(SwapScriptJson));
export const WithdrawALPH = new ExecutableScript<{
  ico: HexString;
  amount: bigint;
}>(Script.fromJson(WithdrawALPHScriptJson));
export const WithdrawToken = new ExecutableScript<{
  ico: HexString;
  amount: bigint;
}>(Script.fromJson(WithdrawTokenScriptJson));
